name: Build and Publish Docker Image

on:
  push:
    branches: [ master ]

jobs:
  docker:
    strategy:
      matrix:
        arch: ['ubuntu-latest']
    runs-on: ${{ matrix.arch }}
    steps:
    - uses: actions/checkout@v3
    - name: Generate Docker metadata
      id: meta
      uses: https://github.com/docker/metadata-action@v3
      with:
        images: |
          gitea.jamesprince.me/${{ github.repository }}
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha
        flavor: |
          latest=true
    - name: setup buildx
      uses: https://github.com/docker/setup-buildx-action@v2
    - name: login into gitea hub
      run: |
        BASE64_AUTH=`echo -n "$CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD" | base64 -w 0`
        mkdir -p ~/.docker
        echo "{\"auths\": {\"$CI_REGISTRY\": {\"auth\": \"$BASE64_AUTH\"}}}" > ~/.docker/config.json
      env:
        CI_REGISTRY: https://gitea.jamesprince.me/
        CI_REGISTRY_USER: ${{ secrets.PACKAGEUSR }}
        CI_REGISTRY_PASSWORD: ${{ secrets.PACKAGEPWD }}
    - name: build image
      uses: https://github.com/docker/build-push-action@v4
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
      env:
        DOCKER_BUILDKIT: 1
        ACTIONS_RUNTIME_TOKEN: ''
