name: ci

on:
  push:
    branches: [ master ]

jobs:
  docker:
    strategy:
      matrix:
        arch: ['ubuntu-latest']
    runs-on: ${{ matrix.arch }}
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - uses: actions/checkout@v3
    - name: setup buildx
      uses: https://github.com/docker/setup-buildx-action@v2
    - name: Login to Gitea@jamesprince.me Container Registry
      uses: https://github.com/docker/login-action@v2
      with:
        registry: https://gitea.jamesprince.me/
        username: ${{ secrets.PACKAGEUSR }}
        password: ${{ secrets.PACKAGEPWD }}
    - name: build image
      uses: https://github.com/docker/build-push-action@v4
      with:
        push: true
        tags: james/iseek_scraper:latest
